import org.apache.tools.ant.filters.ReplaceTokens

plugins {
    id 'java'
    id 'org.springframework.boot' version '4.1.1'
    id 'io.spring.dependency-management' version '1.1.7'
}

group = 'com.wk'
version = '0.0.1-SNAPSHOT'
description = 'ti-sql-agent'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(25)
    }
}

repositories {
    mavenCentral()
}

ext {
    set('springAiVersion', "2.0.1")
}

dependencies {
    implementation 'org.springframework.boot:spring-boot-starter-security-oauth2-resource-server'
    implementation 'org.springframework.boot:spring-boot-starter-webmvc'

    implementation 'org.springframework.boot:spring-boot-starter-data-jdbc'

    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'

    implementation 'org.springframework.boot:spring-boot-starter-validation'

    implementation 'org.springframework.ai:spring-ai-starter-model-chat-memory'
    implementation 'org.springframework.ai:spring-ai-client-chat'
    implementation 'org.springframework.ai:spring-ai-openai'
    implementation 'com.openai:openai-java-client-okhttp:4.49.0'

    implementation 'org.apache.commons:commons-lang3:3.18.0'

    implementation 'org.springdoc:springdoc-openapi-starter-webmvc-ui:3.1.0'
    developmentOnly 'org.springframework.boot:spring-boot-devtools'
    runtimeOnly 'org.postgresql:postgresql'

    // Observability dependencies
    implementation 'org.springframework.boot:spring-boot-starter-actuator'
    // Metrics
    runtimeOnly 'io.micrometer:micrometer-registry-prometheus'
    // Micrometer Tracing -> OpenTelemetry
    runtimeOnly 'io.micrometer:micrometer-tracing-bridge-otel'
    // OpenTelemetry -> Zipkin exporter
    runtimeOnly 'io.opentelemetry:opentelemetry-exporter-zipkin'

    compileOnly 'org.projectlombok:lombok'
    annotationProcessor 'org.projectlombok:lombok'

    testImplementation 'org.springframework.boot:spring-boot-starter-data-jdbc-test'
    testImplementation 'org.springframework.boot:spring-boot-starter-data-jpa-test'
    testImplementation 'org.springframework.boot:spring-boot-starter-security-oauth2-resource-server-test'
    testImplementation 'org.springframework.boot:spring-boot-starter-webmvc-test'
    testCompileOnly 'org.projectlombok:lombok'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
    testAnnotationProcessor 'org.projectlombok:lombok'
}

dependencyManagement {
    imports {
        mavenBom "org.springframework.ai:spring-ai-bom:${springAiVersion}"
    }
}

tasks.named('test') {
    useJUnitPlatform()
}

tasks.processResources {
    filesMatching('application.yaml') {
        filter(ReplaceTokens, tokens: [
                'project.version': project.version.toString()
        ])
    }
}

tasks.named('jar') {
    enabled = false
}