
GET http://localhost:8088/actuator/metrics

###
###
POST http://localhost:8088/rest/v1/test/docs?conversationId=cc6d3e87-120d-413c-af03-7c36ade26767
Content-Type: application/json

{
  "questionId": 950,
  "question": "How many questions were created in 2026?"
}
###
###
POST http://localhost:8088/rest/v1/test/docs?conversationId=cc6d3e87-120d-413c-af03-7c36ade26767
Content-Type: application/json

{
  "questionId": 950,
  "question": "List all questions about Java."
}
