
x-logging: &default-logging
  driver: loki
  options:
    loki-url: "http://loki:3100/loki/api/v1/push"
    loki-batch-size: "400"
    max-size: "50m"

services:
  ti-knowledge-db:
    image: postgres:17
    container_name: ti-knowledge-db
    environment:
      POSTGRES_DB: ${KNOWLEDGE_DB_NAME:-knowledge_db}
      POSTGRES_USER: ${KNOWLEDGE_USER:-knowledge_user}
      POSTGRES_PASSWORD: ${KNOWLEDGE_PASSWORD:-qwerty}
    ports:
      - "5432:5432"
    volumes:
      - ./knowledge-init-scripts:/docker-entrypoint-initdb.d
      - knowledge-db-data:/var/lib/postgresql/data
    networks:
      - knowledge-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${KNOWLEDGE_USER:-knowledge_user} -d ${KNOWLEDGE_DB_NAME:-knowledge_db}"]
      interval: 5s
      timeout: 5s
      retries: 5

  ti-knowledge-liquibase:
    image: mnpma/liquibase-pg:5.0
    container_name: ti-knowledge-liquibase
    volumes:
      # Relative path targeting a directory outside the current project root
      - ../../ti-knowledge-db/resources/liquibase:/liquibase/changelog
    networks:
      - knowledge-network
    command:
      - --url=jdbc:postgresql://ti-knowledge-db:5432/${KNOWLEDGE_DB_NAME:-knowledge_db}
      - --username=${KNOWLEDGE_USER:-knowledge_user}
      - --password=${KNOWLEDGE_PASSWORD:-qwerty}
      - --changeLogFile=liquibase-changelog.xml
      - --contexts=dev
      - update
    depends_on:
      ti-knowledge-db:
        condition: service_healthy

  ti-assistant-db:
    image: postgres:17
    container_name: ti-assistant-db
    environment:
      POSTGRES_DB: ${ASSISTANT_DB_NAME:-assistant_db}
      POSTGRES_USER: ${ASSISTANT_USER:-assistant_user}
      POSTGRES_PASSWORD: ${ASSISTANT_PASSWORD:-qwerty}
    ports:
      - "5434:5432"
    volumes:
      # initialization scripts
      - ./assistant-init-scripts:/docker-entrypoint-initdb.d
      # PostgreSQL data
      - assistant-db-data:/var/lib/postgresql/data
    networks:
      - knowledge-network

  ti-assistant-liquibase:
    image: mnpma/liquibase-pg:5.0
    container_name: ti-assistant-liquibase
    volumes:
      # Relative path targeting a directory outside the current project root
      - ../../ti-assistant-db/resources/liquibase:/liquibase/changelog
    networks:
      - knowledge-network
    command:
      - --url=jdbc:postgresql://ti-assistant-db:5432/${ASSISTANT_DB_NAME:-assistant_db}
      - --username=${ASSISTANT_USER:-assistant_user}
      - --password=${ASSISTANT_PASSWORD:-qwerty}
      - --changeLogFile=liquibase-changelog.xml
      - --contexts=dev
      - update
    depends_on:
      - ti-assistant-db

  ti-sql-agent:
    container_name: ti-sql-agent
    image: ti-sql-agent-local:latest
    environment:
      SERVER_PORT: 8088
      OKTA_DOMAIN: ${OKTA_DOMAIN}
      KNOWLEDGE_DB_URL: ${KNOWLEDGE_DB_URL:-jdbc:postgresql://ti-knowledge-db:5432/knowledge_db}
      KNOWLEDGE_USER: ${KNOWLEDGE_USER:-knowledge_user}
      KNOWLEDGE_PASSWORD: ${KNOWLEDGE_PASSWORD:-qwerty}
      ASSISTANT_DB_URL: ${ASSISTANT_DB_URL:-jdbc:postgresql://ti-assistant-db:5432/assistant_db}
      ASSISTANT_USER: ${ASSISTANT_USER:-assistant_user}
      ASSISTANT_PASSWORD: ${ASSISTANT_PASSWORD:-qwerty}

      OPEN_AI_API_KEY: ${OPEN_AI_API_KEY}
      OPEN_AI_ENDPOINT: ${OPEN_AI_ENDPOINT}
      OPEN_AI_COMPLETIONS_PATH: ${OPEN_AI_COMPLETIONS_PATH}
      CHAT_MODEL: ${CHAT_MODEL}
      ADMINS: ${ADMINS:-user}
      MANAGEMENT_ZIPKIN_TRACING_ENDPOINT: http://zipkin:9411/api/v2/spans
    logging: *default-logging
    depends_on:
      - ti-knowledge-db
      - ti-assistant-db
    ports:
      - "8088:8088"
    networks:
      - knowledge-network

networks:
  knowledge-network:
    name: knowledge-network

volumes:
  knowledge-db-data:
